[book]
title = "Pragmatic Rust Guidelines"
authors = ["Ralf Biedert"]
description = "A collection of pragmatic design guidelines helping service developers to produce idiomatic Rust that scales."
language = "en"
multilingual = false
src = "src"

[output.html]
additional-css = [ "style/tags.css", "style/fixes.css", "style/guideline-meta.css" ]

[output.html.print]
enable = true

# Enable for PDF, disable otherwise (it'd run all the time even in dev mode)
#
# [output.pdf]
# print-background = true
# generate-tagged-pdf = true
# theme = "light"
