name: Common Steps

on:
  workflow_call:

jobs:
  Tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install mdBook
      run: |
        mkdir -p ~/.local/bin
        curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar xz -C ~/.local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Linting Markdown Files
      uses: DavidAnson/markdownlint-cli2-action@v20
      with:
        globs: '**/*.md'

    - name: MdBook Test
      run: |
        mdbook test

    - name: Preprocess
      run: |
        chmod +x ./scripts/*.sh
        bash ./scripts/update_agents.sh
        bash ./scripts/update_meta.sh
      
    - name: Build
      run: mdbook build
      
    - name: Upload book artifact
      uses: actions/upload-artifact@v4
      with:
        name: book
        path: book/